services:
  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: kotatsu_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    container_name: kotatsu-sync
    build: ./
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: your_user
      DATABASE_PASSWORD: your_password
      DATABASE_NAME: kotatsu_db
      DATABASE_PORT: 3306
      JWT_SECRET: your_secret
      ALLOW_NEW_REGISTER: true
    restart: always